/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/persona": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions with cursor-based pagination */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Session ID to paginate after */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated session list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new persona session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePersonaRequest"];
                };
            };
            responses: {
                /** @description Session created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatePersonaResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/persona/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get session info and persona definition */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session info with persona */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            personaName: string;
                            createdAt: number;
                            lastActive: number;
                            persona?: unknown;
                        };
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            deleted: true;
                        };
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process a conversation turn */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProcessTurnRequest"];
                };
            };
            responses: {
                /** @description Turn processed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TurnResultResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turn/appraisal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process a turn from an external appraisal vector */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProcessAppraisalRequest"];
                };
            };
            responses: {
                /** @description Turn processed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TurnResultResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/state/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current emotion state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current emotion state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StateResponse"];
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proactive/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check pending proactive actions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Proactive actions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProactiveResponse"];
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proactive/{sessionId}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set proactive preferences */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProactivePreferences"];
                };
            };
            responses: {
                /** @description Preferences updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            updated: true;
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/relationship/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get relationship state and unhealthy pattern analysis */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Relationship state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelationshipResponse"];
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhook/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhooks for a session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Webhook list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Register a webhook for a session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterWebhookRequest"];
                };
            };
            responses: {
                /** @description Webhook registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhook/{sessionId}/{webhookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                    webhookId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            deleted: true;
                        };
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available persona presets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Available persona presets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListPresetsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePersonaResponse: {
            sessionId: string;
            personaName: string;
            prompt_data: components["schemas"]["PersonaPromptData"];
        };
        PersonaPromptData: {
            system: components["schemas"]["PromptDataSystem"];
        };
        PromptDataSystem: {
            identity: {
                name: string;
                role: string | null;
                core_values: string[];
                speaking_style: string;
            };
            traits: {
                [key: string]: {
                    value: number;
                    level: string;
                    behavior: string;
                };
            };
            goals: {
                content: string;
                priority: number;
                mutable: boolean;
            }[];
            formatted: {
                system_prompt: string;
            };
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        CreatePersonaRequest: {
            persona: {
                identity: {
                    name: string;
                    role?: string;
                    core_values: string[];
                    speaking_style: string;
                };
                personality?: components["schemas"]["Personality"];
                /** @description Emotion dynamics configuration. Required when preset is not used. */
                emotion_config?: {
                    baseline: components["schemas"]["VAD"];
                    damping_ratio: number;
                    natural_freq: number;
                    inertia_coefficient: number;
                    appraisal_weights: {
                        valence: number[];
                        arousal: number[];
                        dominance: number[];
                    };
                };
                /** @description Character goals. Required when preset is not used. */
                goals?: {
                    content: string;
                    priority: number;
                    mutable: boolean;
                }[];
            };
            /**
             * @description Persona preset name. When used, personality/emotion_config/goals are auto-filled from the preset and can be individually overridden.
             * @example cheerful_companion
             */
            preset?: string;
            config?: {
                memory?: {
                    emotionHistorySize?: number;
                };
                calibration?: {
                    /**
                     * @description Body budget recovery rate per hour
                     * @example 0.125
                     */
                    budgetRecoveryPerHour?: number;
                    /**
                     * @description Body budget minimum floor
                     * @example 0.05
                     */
                    budgetMinimum?: number;
                    /**
                     * @description Time normalization base (seconds per dt=1.0)
                     * @example 30
                     */
                    turnScale?: number;
                };
            };
        };
        /** @description HEXACO personality traits. Required when preset is not used. */
        Personality: {
            O: number;
            C: number;
            E: number;
            A: number;
            N: number;
            H: number;
        };
        VAD: {
            V: number;
            A: number;
            D: number;
        };
        SessionListResponse: {
            items: {
                id: string;
                personaName: string;
                createdAt: number;
                lastActive: number;
            }[];
            cursor: string | null;
        };
        TurnResultResponse: {
            appraisal: components["schemas"]["AppraisalVector"];
            prediction_error: {
                relevance: number;
                congruence: number;
                expectedness: number;
                controllability: number;
                agency: number;
                norm_compatibility: number;
                magnitude: number;
            };
            emotion_delta: components["schemas"]["VAD"];
            new_emotion: components["schemas"]["VAD"];
            emotion_intensity: number;
            discrete_emotion: components["schemas"]["DiscreteEmotionDetail"];
            stage_transition: boolean;
            response: string;
            body_budget: number;
            soul_stage: {
                id: number;
                name: string;
            };
            velocity: components["schemas"]["Velocity"];
            blend_ratio: components["schemas"]["BlendRatio"];
            regulation: components["schemas"]["RegulationSnapshot"];
            catastrophe: components["schemas"]["CatastropheSnapshot"];
            proactive_hint: components["schemas"]["ProactiveHint"];
            prompt_data: components["schemas"]["TurnPromptData"];
        };
        AppraisalVector: {
            goal_relevance: number;
            goal_congruence: number;
            expectedness: number;
            controllability: number;
            agency: number;
            norm_compatibility: number;
        };
        DiscreteEmotionDetail: {
            primary: string;
            secondary: string | null;
            intensity: string;
        };
        Velocity: {
            V: number;
            A: number;
            D: number;
        };
        BlendRatio: {
            rational: number;
            irrational: number;
        };
        RegulationSnapshot: {
            strategy: string;
            phase: string;
            progress: number;
        } | null;
        CatastropheSnapshot: {
            alpha: number;
            beta: number;
        };
        ProactiveHint: {
            next_check_after_ms: number;
            potential_triggers: string[];
        };
        TurnPromptData: {
            context: components["schemas"]["PromptDataContext"];
            instruction: components["schemas"]["PromptDataInstruction"];
        };
        PromptDataContext: {
            event_context: string | null;
            emotion: {
                primary: string;
                secondary: string | null;
                intensity_level: string;
                valence_description: string;
                arousal_description: string;
                dominance_description: string;
            };
            energy: {
                level: string;
                budget_percentage: number;
                description: string;
            };
            stage: {
                name: string;
                description: string;
                behavioral_tendency: string;
            };
            blend: {
                dominant: string;
                ratio_description: string;
                mask_integrity: number;
                mask_state: string;
            };
            regulation: {
                active: boolean;
                strategy_name: string | null;
                phase_name: string | null;
                description: string;
            };
            velocity: {
                direction: string;
                description: string;
            };
            catastrophe: {
                risk_level: string;
                description: string;
            };
            formatted: {
                context_block: string;
            };
        };
        PromptDataInstruction: {
            stage_instruction: string;
            expression_guide: string;
            response_length_hint: string;
            mask_guidance: string;
            need_direction: string | null;
            goal_modulation: {
                content: string;
                original_priority: number;
                effective_priority: number;
                note: string | null;
            }[];
            formatted: {
                instruction_block: string;
            };
        };
        ProcessTurnRequest: {
            sessionId: string;
            message?: string;
            event?: {
                description: string;
                /** @enum {string} */
                source: "user" | "system" | "internal";
                timestamp?: number;
            };
            elapsedSeconds?: number;
        };
        ProcessAppraisalRequest: {
            sessionId: string;
            appraisal: components["schemas"]["AppraisalVector"];
            /** @description What happened — passed through to prompt_data for response generation */
            context?: string;
            elapsedSeconds?: number;
        };
        StateResponse: {
            emotion: components["schemas"]["VAD"];
            emotion_intensity: number;
            discrete_emotion: components["schemas"]["DiscreteEmotionDetail"];
            body_budget: number;
            soul_stage: {
                id: number;
                name: string;
            };
            need_state?: {
                autonomy: number;
                competence: number;
                relatedness: number;
            };
            interpersonal: {
                dominance: number;
                affiliation: number;
            };
            affect_dynamics: {
                variability: number;
                instability: number;
                inertia_observed: number;
            };
            emotion_summary: string;
            velocity: components["schemas"]["Velocity"];
            blend_ratio: components["schemas"]["BlendRatio"];
            regulation: {
                active_strategy: components["schemas"]["RegulationSnapshot"];
                strategy_weights: {
                    [key: string]: number;
                };
            };
            catastrophe: components["schemas"]["CatastropheFull"];
            prediction_model: components["schemas"]["AppraisalVector"];
            metacog: components["schemas"]["MetacogSnapshot"];
            prevMaskIntegrity: number | null;
            prompt_data: components["schemas"]["StatePromptData"];
        };
        CatastropheFull: {
            alpha: number;
            beta: number;
            z: number;
            hysteresis_bound: number;
        };
        MetacogSnapshot: {
            turns_since_check: number;
            self_awareness: string;
        };
        StatePromptData: {
            system: components["schemas"]["PromptDataSystem"];
            context: components["schemas"]["PromptDataContextFull"];
            instruction: components["schemas"]["PromptDataInstruction"];
        };
        PromptDataContextFull: components["schemas"]["PromptDataContext"] & {
            needs?: {
                autonomy: {
                    value: number;
                    level: string;
                    description: string;
                };
                competence: {
                    value: number;
                    level: string;
                    description: string;
                };
                relatedness: {
                    value: number;
                    level: string;
                    description: string;
                };
                deficit_summary: string | null;
            };
            interpersonal?: {
                dominance_level: string;
                affiliation_level: string;
                description: string;
            };
            relationship: {
                trust_level: string;
                trust_percentage: number;
                attachment_style: string;
                attachment_description: string;
                stage: string;
                intimacy_level: string;
            } | null;
            metacog: {
                awareness_level: string;
                description: string;
            };
            affect_dynamics: {
                stability: string;
                description: string;
            };
        };
        ProactiveResponse: {
            actions: components["schemas"]["ProactiveOutput"][];
            next_check_after_ms: number;
            idle_ms: number;
        };
        ProactiveOutput: {
            id: string;
            /** @enum {string} */
            trigger: "attachment_seeking" | "need_deficit" | "emotional_overflow" | "concern" | "idle_reconnection";
            importance: number;
            timestamp: number;
            psychological_context: {
                emotion: components["schemas"]["VAD"];
                discrete_emotion: string;
                emotion_intensity: number;
                body_budget: number;
                need_deficits?: {
                    autonomy: number;
                    competence: number;
                    relatedness: number;
                };
            };
            metadata?: {
                expects_response: boolean;
                expires_at?: number;
                tags?: string[];
            };
        };
        ProactivePreferences: {
            enabled: boolean;
            /** @default 3 */
            maxDailyMessages: number;
            quietHours: {
                start: number;
                end: number;
            };
            minInterval: number;
            urgencyThreshold: number;
        };
        RelationshipResponse: {
            relationship: components["schemas"]["RelationshipState"];
            unhealthy_patterns: components["schemas"]["UnhealthyPatternResult"];
            trust_description: string;
            attachment_description: string;
        };
        RelationshipState: {
            duration_days: number;
            trust_level: number;
            /** @enum {string} */
            attachment_style: "secure" | "anxious" | "avoidant" | "disorganized";
            interaction_count: number;
            positive_ratio: number;
            stage: string;
            intimacy: number;
            secure_base: boolean;
            proximity_need: number;
        };
        UnhealthyPatternResult: {
            patternDetected: boolean;
            /** @enum {string} */
            patternType?: "excessive_dependency" | "avoidant_withdrawal" | "anxious_avoidant_oscillation";
            severity: number;
            recommendedAction?: {
                boundaryFirmness: number;
                supportIntensity: number;
                initiativeLevel: number;
            };
        };
        WebhookResponse: {
            id: string;
            session_id: string;
            url: string;
            events: string[];
            created_at: number;
        };
        RegisterWebhookRequest: {
            /** Format: uri */
            url: string;
            /** @description Shared secret for HMAC-SHA256 signature verification */
            secret?: string;
            /**
             * @default [
             *       "proactive"
             *     ]
             */
            events: components["schemas"]["WebhookEvent"][];
        };
        /** @enum {string} */
        WebhookEvent: "proactive";
        WebhookListResponse: {
            webhooks: components["schemas"]["WebhookResponse"][];
        };
        ListPresetsResponse: {
            presets: components["schemas"]["PresetList"];
        };
        PresetList: {
            /** @example cheerful_companion */
            name: string;
            /** @example Warm and upbeat personality */
            description: string;
            personality: {
                O: number;
                C: number;
                E: number;
                A: number;
                N: number;
                H: number;
            };
            goals: {
                content: string;
                priority: number;
                mutable: boolean;
            }[];
        }[];
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example 0.1.0 */
            version: string;
            /** @example d1 */
            storage: string;
            /** @example 0 */
            sessions: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
